# Generated by Django 5.2.2 on 2025-06-05 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('contrato', 'Contrato'), ('poder', 'Poder'), ('declaracion', 'Declaración')], max_length=50)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(default='pendiente', max_length=20)),
                ('ruta', models.CharField(max_length=500)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='empresas.empresa')),
            ],
        ),
    ]
