# Generated by Django 5.2.2 on 2025-06-07 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='ruta',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='tipo',
        ),
        migrations.AddField(
            model_name='documento',
            name='archivo',
            field=models.FileField(default='', upload_to='documentos/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documento',
            name='nombre',
            field=models.CharField(default='hola', max_length=255),
            preserve_default=False,
        ),
    ]
