# Generated by Django 5.2.2 on 2025-06-13 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0002_remove_documento_estado_remove_documento_ruta_and_more'),
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='contenido',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documento',
            name='etiquetas',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='documento',
            name='tipo_documento',
            field=models.CharField(choices=[('contrato', 'Contrato'), ('poder', 'Poder'), ('carta', 'Carta de presentación'), ('declaracion', 'Declaración jurada')], default='contrato', max_length=50),
        ),
        migrations.AlterField(
            model_name='documento',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa'),
        ),
    ]
