# Generated by Django 5.2.2 on 2025-06-13 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0004_firma'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firma',
            name='fecha_solicitud',
        ),
        migrations.RemoveField(
            model_name='firma',
            name='observaciones',
        ),
        migrations.RemoveField(
            model_name='firma',
            name='proveedor',
        ),
        migrations.AddField(
            model_name='firma',
            name='ip_firma',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='firma',
            name='trazabilidad',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='firma',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('firmado', 'Firmado')], default='pendiente', max_length=20),
        ),
    ]
