# Generated by Django 5.2.2 on 2025-06-16 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0005_remove_firma_fecha_solicitud_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='firma',
            name='firma_imagen',
            field=models.ImageField(blank=True, null=True, upload_to='firmas/'),
        ),
    ]
