# Generated by Django 5.2.2 on 2025-06-17 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0006_firma_firma_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='archivo_firmado',
            field=models.FileField(blank=True, null=True, upload_to='firmados/'),
        ),
    ]
