# Generated by Django 5.2.2 on 2025-06-17 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0007_documento_archivo_firmado'),
    ]

    operations = [
        migrations.AddField(
            model_name='firma',
            name='posicion',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
