# Generated by Django 5.2.2 on 2025-06-18 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0008_firma_posicion'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='archivo_firmado_visual',
            field=models.FileField(blank=True, null=True, upload_to='firmados_visual/'),
        ),
    ]
