# Generated by Django 5.2.2 on 2025-06-20 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0009_documento_archivo_firmado_visual'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='creador',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, related_name='documentos_creados', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
