# Generated by Django 5.2.2 on 2025-06-28 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_estrategia_etapa_actividad'),
        ('empresas', '0013_actividad_fecha_completada_actividad_notas_mentor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BotFeeding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('texto_libre', 'Texto Libre'), ('estrategia_referencia', 'Estrategia de Referencia')], max_length=50)),
                ('contenido', models.TextField(help_text='Contenido usado para alimentar al bot')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activa', models.BooleanField(default=True, help_text='Si esta alimentación está activa para el bot')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alimentaciones', to='chat.chatcategory')),
                ('estrategia_referencia', models.ForeignKey(blank=True, help_text="Estrategia usada como referencia (solo si tipo es 'estrategia_referencia')", null=True, on_delete=django.db.models.deletion.CASCADE, to='empresas.estrategia')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alimentaciones_bot', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alimentación de Bot',
                'verbose_name_plural': 'Alimentaciones de Bot',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
