# Generated by Django 5.2.2 on 2025-06-13 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('empresa', 'Administrador Empresa'), ('mentor', 'Mentor'), ('superadmin', 'Superadmin'), ('editor', 'Editor'), ('lector', 'Lector')], max_length=20),
        ),
    ]
