# Generated by Django 5.2.2 on 2025-06-16 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_usuario_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='clave_firma',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
