# Generated by Django 5.2.2 on 2025-06-19 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_usuario_clave_firma'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='rol_interno',
            field=models.CharField(blank=True, choices=[('representante', 'Representante legal'), ('socio', 'Socio/accionista'), ('administrador', 'Administrador de empresa'), ('contador', 'Contador/asesor legal interno'), ('empleado', 'Empleado operativo')], default='empleado', max_length=30, null=True),
        ),
    ]
