# Generated by Django 5.2.2 on 2025-06-28 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_usuario_rol_interno'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='especialidades',
            field=models.CharField(blank=True, choices=[('marketing', 'Marketing Digital'), ('finanzas', 'Finanzas y Contabilidad'), ('recursos_humanos', 'Recursos Humanos'), ('operaciones', 'Operaciones y Logística'), ('tecnologia', 'Tecnología e Innovación'), ('ventas', 'Ventas y Comercialización'), ('legal', 'Legal y Compliance'), ('estrategia', 'Estrategia Empresarial'), ('liderazgo', 'Liderazgo y Gestión'), ('internacional', 'Comercio Internacional')], help_text='Solo para usuarios con rol de mentor', max_length=50, null=True),
        ),
    ]
