# Generated by Django 5.2.2 on 2025-06-28 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_usuario_especialidades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='especialidades',
            field=models.CharField(blank=True, choices=[('marketing_digital', 'Marketing Digital'), ('acceso_a_financiamiento', 'Acceso a Financiamiento'), ('innovacion_y_desarrollo_de_productos', 'Innovación y Desarrollo de Productos'), ('branding', 'Branding'), ('diseno_y_desarrollo_ux_ui', 'Diseño y Desarrollo UX/UI'), ('seo_en_la_era_de_la_ia', 'SEO en la Era de la IA'), ('finanzas', 'Finanzas y Contabilidad'), ('recursos_humanos', 'Recursos Humanos'), ('operaciones', 'Operaciones y Logística'), ('tecnologia', 'Tecnología e Innovación'), ('ventas', 'Ventas y Comercialización'), ('legal', 'Legal y Compliance'), ('estrategia', 'Estrategia Empresarial'), ('general', 'General (Todas las áreas)')], help_text="Solo para usuarios con rol de mentor. 'General' permite ver todas las solicitudes.", max_length=50, null=True),
        ),
    ]
