# Generated by Django 5.2.2 on 2025-06-18 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0004_estrategia_categoria_estrategia_fecha_cumplimiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='historia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='mision',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='objetivo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='valores',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='vision',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='web',
            field=models.URLField(blank=True, null=True),
        ),
    ]
