# Generated by Django 5.2.2 on 2025-06-19 02:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0005_empresa_facebook_empresa_historia_empresa_instagram_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='mentores',
            field=models.ManyToManyField(blank=True, limit_choices_to={'rol': 'mentor'}, related_name='empresas_asesoradas', to=settings.AUTH_USER_MODEL),
        ),
    ]
