# Generated by Django 5.2.2 on 2025-06-19 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0006_empresa_mentores'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='solicita_mentoria',
            field=models.BooleanField(default=False),
        ),
    ]
