# Generated by Django 5.2.2 on 2025-06-20 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0007_empresa_solicita_mentoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad',
            name='estrategia',
        ),
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Etapa sin nombre', max_length=255)),
                ('descripcion', models.TextField(blank=True, default='Descripción de la etapa', null=True)),
                ('estrategia', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='empresas.estrategia')),
            ],
        ),
        migrations.AddField(
            model_name='actividad',
            name='etapa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='empresas.etapa'),
        ),
    ]
