# Generated by Django 5.2.2 on 2025-06-28 05:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0008_remove_actividad_estrategia_etapa_actividad_etapa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='solicita_mentoria',
        ),
        migrations.AddField(
            model_name='estrategia',
            name='especialidad_requerida',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='estrategia',
            name='fecha_asignacion_mentor',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estrategia',
            name='fecha_solicitud_mentoria',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estrategia',
            name='mentor_asignado',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol': 'mentor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estrategias_mentoreadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='estrategia',
            name='solicita_mentoria',
            field=models.BooleanField(default=False),
        ),
    ]
