# Generated by Django 5.2.2 on 2025-06-28 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0009_remove_empresa_solicita_mentoria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='mentores',
        ),
    ]
