# Generated by Django 5.2.2 on 2025-06-28 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0010_remove_mentores_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='orden',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='etapa',
            name='orden',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='etapa',
            name='titulo',
            field=models.CharField(default='Etapa sin nombre', max_length=255),
        ),
    ]
