# Generated by Django 5.2.2 on 2025-06-28 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0011_actividad_orden_etapa_orden_etapa_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estrategia',
            name='especialidad_requerida',
            field=models.CharField(blank=True, help_text='Especialidad requerida del mentor. Debe coincidir con las especialidades definidas en el modelo Usuario.', max_length=100, null=True),
        ),
    ]
