# Generated by Django 5.2.2 on 2025-06-28 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0012_alter_estrategia_especialidad_requerida'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='fecha_completada',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='actividad',
            name='notas_mentor',
            field=models.TextField(blank=True, help_text='Notas del mentor sobre esta actividad', null=True),
        ),
    ]
